/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui;

import com.controler.LoginControler;
import com.controler.UserControler;
import com.model.Account;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

/**
 *
 * @author AnataArisa
 */
public class Menu extends javax.swing.JFrame {

    private Account account;
    private UserControler user;
    private LoginFrame login;
    private LoginControler lc;
    private Thread check;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    public Menu(Account account, UserControler user, LoginControler lc, LoginFrame login) {
        this.account = account;
        this.user = user;
        this.login = login;
        this.lc = lc;
        initComponents();
        name.setText(account.getName());
        check = new Thread(new Runnable() {
            @Override
            public void run() {
                if (null == user.getPubList()) {
                    book_btn.setEnabled(false);
                } else {
                    book_btn.setEnabled(true);
                }
            }
        }
        );
        check.start();
    }

    public Menu(Account account, UserControler user, LoginControler lc) {
        this.account = account;
        this.user = user;
        this.login = new LoginFrame(user, lc);
        this.lc = lc;
        initComponents();
        name.setText(account.getName());
        check = new Thread(new Runnable() {
            @Override
            public void run() {
                if (null == user.getPubList()) {
                    book_btn.setEnabled(false);
                } else {
                    book_btn.setEnabled(true);
                }
            }
        }
        );
        check.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        name = new JLabel();
        jPanel2 = new JPanel();
        createAcc_btn = new JButton();
        book_btn = new JButton();
        exit = new JButton();
        pub_btn = new JButton();
        jLabel3 = new JLabel();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Terminal");
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        setIconImage(new ImageIcon("src//com//gui//img//app.png").getImage());
        setName("Form"); // NOI18N
        setSize(new Dimension(1920, 1080));

        jPanel1.setBackground(new Color(153, 255, 153));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(new Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new Color(255, 255, 255));
        jLabel1.setText("WELCOME");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new Color(255, 255, 255));
        jLabel2.setText("MENU TERMINAL");
        jLabel2.setName("jLabel2"); // NOI18N

        name.setFont(new Font("Segoe UI", 1, 36)); // NOI18N
        name.setForeground(new Color(255, 255, 255));
        name.setText("nqv");
        name.setName("name"); // NOI18N

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, GroupLayout.Alignment.TRAILING)
                    .addComponent(name, GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        name.getAccessibleContext().setAccessibleName("name");

        jPanel2.setName("jPanel2"); // NOI18N

        createAcc_btn.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        createAcc_btn.setText("CREATE ACCOUNT");
        createAcc_btn.setName("createAcc_btn"); // NOI18N
        createAcc_btn.addActionListener(formListener);

        book_btn.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        book_btn.setText("BOOK");
        book_btn.setName("book_btn"); // NOI18N
        book_btn.addActionListener(formListener);

        exit.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        exit.setText("EXIT");
        exit.setName("exit"); // NOI18N
        exit.addActionListener(formListener);

        pub_btn.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        pub_btn.setText("PUBLISHER");
        pub_btn.setName("pub_btn"); // NOI18N
        pub_btn.addActionListener(formListener);

        jLabel3.setText("DESIGN BY NGUYEN QUANG VINH");
        jLabel3.setName("jLabel3"); // NOI18N

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(515, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(pub_btn, GroupLayout.PREFERRED_SIZE, 188, GroupLayout.PREFERRED_SIZE)
                        .addGap(531, 531, 531))
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(createAcc_btn, GroupLayout.PREFERRED_SIZE, 299, GroupLayout.PREFERRED_SIZE)
                        .addGap(466, 466, 466))
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(exit, GroupLayout.PREFERRED_SIZE, 188, GroupLayout.PREFERRED_SIZE)
                        .addGap(526, 526, 526))
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(41, 41, 41))))
            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(583, Short.MAX_VALUE)
                    .addComponent(book_btn, GroupLayout.PREFERRED_SIZE, 138, GroupLayout.PREFERRED_SIZE)
                    .addGap(559, 559, 559)))
        );
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(pub_btn)
                .addGap(64, 64, 64)
                .addComponent(createAcc_btn)
                .addGap(72, 72, 72)
                .addComponent(exit)
                .addGap(125, 125, 125)
                .addComponent(jLabel3)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(book_btn)
                    .addContainerGap(480, Short.MAX_VALUE)))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements ActionListener {
        FormListener() {}
        public void actionPerformed(ActionEvent evt) {
            if (evt.getSource() == createAcc_btn) {
                Menu.this.createAcc_btnActionPerformed(evt);
            }
            else if (evt.getSource() == book_btn) {
                Menu.this.book_btnActionPerformed(evt);
            }
            else if (evt.getSource() == exit) {
                Menu.this.exitActionPerformed(evt);
            }
            else if (evt.getSource() == pub_btn) {
                Menu.this.pub_btnActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void book_btnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_book_btnActionPerformed
        BookTerminal bookT = new BookTerminal(user, this);
        bookT.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_book_btnActionPerformed

    private void pub_btnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_pub_btnActionPerformed
        PublisherTerminal pubT = new PublisherTerminal(user, this);
        pubT.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pub_btnActionPerformed

    private void createAcc_btnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_createAcc_btnActionPerformed
        RegisterAccount rc = new RegisterAccount(this, lc);
        this.setVisible(false);
        rc.setVisible(true);
    }//GEN-LAST:event_createAcc_btnActionPerformed

    private void exitActionPerformed(ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.setVisible(false);
        login.setVisible(true);
        login.getPassword().setText("");
        account = null;
        lc.deleteSession();
        if(check != null) check.yield();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton book_btn;
    private JButton createAcc_btn;
    private JButton exit;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JLabel name;
    private JButton pub_btn;
    // End of variables declaration//GEN-END:variables
}
