/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui;

import com.controler.UserControler;
import com.model.Publisher;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.controler.Noficiation;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import my.lib.Validate;

/**
 *
 * @author AnataArisa
 */
public class PublisherTerminal extends javax.swing.JFrame {

    private UserControler user;
    private Menu menu;
    private Noficiation nofi;
    private TableControler tc = new TableControler();
    /**
     * Creates new form PublisherTerminal
     */
    public PublisherTerminal() {
        tc.start();
        initComponents();
    }

    public PublisherTerminal(UserControler user, Menu menu) {
        this.user = user;
        this.menu = menu;
        initComponents();
        tc.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phonenum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pubtable = new javax.swing.JTable();
        delete_btn = new javax.swing.JButton();
        create_btn = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        exit_btn = new javax.swing.JButton();
        search_btn = new javax.swing.JButton();
        phonemess = new javax.swing.JLabel();
        pidmess = new javax.swing.JLabel();
        namemess = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Publisher Terminal");
        setIconImage(new ImageIcon("src//com//gui//img//book.png").getImage());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("PUBLISHER TERMINAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        panel.setEnabled(false);
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ID.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDFocusLost(evt);
            }
        });
        panel.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 119, 388, 63));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("PUBLISHER ID");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 81, -1, -1));

        name.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        panel.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 388, 63));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("PUBLISHER NAME");
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        phonenum.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        phonenum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                phonenumFocusLost(evt);
            }
        });
        panel.add(phonenum, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 388, 63));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("PHONE NUMBER");
        panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        pubtable.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        pubtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Publisher ID", "Name", "Phone number"
            }
        ));
        pubtable.setToolTipText("");
        jScrollPane1.setViewportView(pubtable);

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 0, 1238, 759));

        delete_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        panel.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 710, 130, 61));

        create_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        create_btn.setText("Create");
        create_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_btnActionPerformed(evt);
            }
        });
        panel.add(create_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 710, 130, 61));

        message.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        message.setForeground(new java.awt.Color(255, 51, 51));
        message.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        panel.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 790, 930, 40));

        exit_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exit_btn.setText("Exit");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        panel.add(exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 710, 130, 61));

        search_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        panel.add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 710, 130, 61));

        phonemess.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        phonemess.setForeground(new java.awt.Color(255, 51, 51));
        phonemess.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        panel.add(phonemess, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 430, 40));

        pidmess.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pidmess.setForeground(new java.awt.Color(255, 51, 51));
        pidmess.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        panel.add(pidmess, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 440, 40));

        namemess.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namemess.setForeground(new java.awt.Color(255, 51, 51));
        namemess.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        panel.add(namemess, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 440, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        String pID = ID.getText();
        Publisher data = new Publisher(pID);
        boolean temp = user.deletePublisher(data);
        if (temp == false) {
            message.setText("Failed");
        } else {
            message.setText("Success!!!");
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void create_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_btnActionPerformed
        // TODO add your handling code here:
        String id = ID.getText();
        String pName = name.getText();
        String phoneNum = phonenum.getText();
        Publisher dataIn = new Publisher(id, pName, phoneNum);
        boolean temp = user.addPublisher(dataIn);
        if (temp == false) {
            messageSystem("Failed!!!");
        } else {
            messageSystem("Success!!!");
            tc.resetTable(1);
        }
    }//GEN-LAST:event_create_btnActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        tc.stopTable();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_exit_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        String id = ID.getText();
        Publisher temp = user.searchPublisherByID(id);
        if (temp != null) {
            name.setText(temp.getName());
            phonenum.setText(temp.getPhoneNumber());
            messageSystem("Found!!!");
        } else {
            messageSystem("Notfound!!!");
        }
    }//GEN-LAST:event_search_btnActionPerformed

    private void IDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFocusLost
        // TODO add your handling code here:
        if(ID.getText().isEmpty()) messageSystem("PID is empty, please check again", pidmess);
        else{
            if(!ID.getText().matches("P[\\d]{5}")){
                messageSystem("PID is not match format, please try again!!!", pidmess);
            }
        }
    }//GEN-LAST:event_IDFocusLost

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        // TODO add your handling code here:
        if(name.getText().isEmpty()) messageSystem("Name is empty, please check again", namemess);
        else{
            if(!Validate.stringValidationSize(name.getText(),5, 30)){
                messageSystem("Name is not length enough, please try again!!!",namemess);
            }
        }
    }//GEN-LAST:event_nameFocusLost

    private void phonenumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonenumFocusLost
        // TODO add your handling code here:
        if(phonenum.getText().isEmpty()) messageSystem("Phone number is empty, please try again !!!",phonemess);
        else{
            if(!Validate.phoneValidate(phonenum.getText(), 9, 12)){
                messageSystem("Phone num is not right format, please try again !!!", phonemess);
            }
        }
    }//GEN-LAST:event_phonenumFocusLost

    private void messageSystem(String mess) {
        nofi = new Noficiation(message);
        nofi.setContent(mess);
        nofi.start();
    }
    
    private void messageSystem(String mess, JLabel temp){
        nofi = new Noficiation(temp);
        nofi.setContent(mess);
        nofi.start();
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JButton create_btn;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton exit_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel message;
    private javax.swing.JTextField name;
    private javax.swing.JLabel namemess;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel phonemess;
    private javax.swing.JTextField phonenum;
    private javax.swing.JLabel pidmess;
    private javax.swing.JTable pubtable;
    private javax.swing.JButton search_btn;
    // End of variables declaration//GEN-END:variables
private class TableControler extends Thread {
        Thread tbThread = null;
        int size = 0;
        public TableControler(){
            tbThread = this;
        }
        List<Publisher> temp;
        @Override
        public void run() {
            boolean status = true;
            size = 0;
            while (true) {
                temp = user.getPubList();
                temp.sort(new Publisher());
                if (temp != null) {
                    if (size < temp.size()) {
                        for (int i = size; i < temp.size(); i++) {
                            Publisher t = temp.get(i);
                            String[] rowData = {t.getpID(), t.getName(), t.getPhoneNumber()};
                            DefaultTableModel tm = (DefaultTableModel) pubtable.getModel();
                            tm.addRow(rowData);
                        }
                        size = temp.size();
                    }
                }
                try {
                    Thread.sleep(100);
                } catch (InterruptedException ex) {
                    Logger.getLogger(PublisherTerminal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        public void stopTable(){
            this.yield();
        }
        @Override
        public void start(){
            tbThread = new Thread(this);
            tbThread.start();
        }
        
        public void resetTable(int mode){
            DefaultTableModel tm = (DefaultTableModel) pubtable.getModel();
            tm.setRowCount(0);
            size = 0;
            if(mode == 1 && !this.isAlive()) this.start();
        }
    }
}
