/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui;

import com.controler.LoginControler;
import com.model.Account;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author AnataArisa
 */
public class RegisterAccount extends javax.swing.JFrame {

    private Menu menu;
    private LoginControler lc;

    /**
     * Creates new form RegisterAccount
     */
    public RegisterAccount() {
        initComponents();
    }

    public RegisterAccount(Menu menu, LoginControler lc) {
        this.menu = menu;
        this.lc = lc;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        message = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        repass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        register_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register Terminal");
        setBackground(new java.awt.Color(51, 255, 51));
        setIconImage(new ImageIcon("src//com//gui//img//book.png").getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 0));
        jPanel1.setForeground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("REGISTER ACCOUNT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 130));

        username.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameKeyPressed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 810, 60));

        message.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        message.setForeground(new java.awt.Color(255, 0, 0));
        message.setText("SYSTEM SYANDBY");
        getContentPane().add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 640, 50));

        password.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 810, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        repass.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        repass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                repassKeyPressed(evt);
            }
        });
        getContentPane().add(repass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 810, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("REPASS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, -1));

        name.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 810, 60));

        register_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        register_btn.setText("REGISTER");
        register_btn.setToolTipText("");
        register_btn.setActionCommand("");
        register_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_btnActionPerformed(evt);
            }
        });
        getContentPane().add(register_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 630, 130, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("USER NAME");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exit.setText("EXIT");
        exit.setToolTipText("");
        exit.setActionCommand("");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 630, 130, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            username.transferFocus();
    }//GEN-LAST:event_usernameKeyPressed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            password.transferFocus();
    }//GEN-LAST:event_passwordKeyPressed

    private void repassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_repassKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            repass.transferFocus();
    }//GEN-LAST:event_repassKeyPressed

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!registerAccount()) {
                message.setText("Register failed, username matched !!!");
            } else {
                message.setText("Register success !!!");
            }
        }
    }//GEN-LAST:event_nameKeyPressed

    private void register_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_btnActionPerformed
        // TODO add your handling code here:
        if (!registerAccount()) {
            message.setText("Register failed, username matched !!!");
        } else
            message.setText("Register success !!!");
    }//GEN-LAST:event_register_btnActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    private boolean registerAccount() {
        if (username.getText().isEmpty() || password.getText().isEmpty() || repass.getText().isEmpty() || name.getText().isEmpty()) {
            return false;
        }
        if (password.getText().equals(repass.getText())) {
            Account temp = new Account(username.getText(), password.getText(), name.getText());
            return lc.registerAccount(temp);
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel message;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    private javax.swing.JButton register_btn;
    private javax.swing.JTextField repass;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
